return {
	enabled = true,
	safeMode = true,
	farmNormalBreakables = true,
	farmBreakableClasses = { "Normal", "Present", "Gift", "MiniChest", "Chest" },
	-- Часть random events (Coin Jar coins и т.д.) регистрируется в BreakableFrontend, но не попадает в типичные классы — добираем по BreakableUID на партях под __THINGS.RandomEvents.
	farmMergeRandomEventBreakableParts = true,
	farmPrioritizeRandomEventBreakables = true,
	delayDamage = 0.16,
	farmRadius = 420,
	preferClosest = true,
	farmCandidateScanInterval = 0.12,
	collectOrbs = true,
	orbCollectInterval = 0.35,
	maxOrbBatch = 80,
	orbAccumulatorMaxKeys = 4000,
	orbMagnetBoost = true,
	orbMagnetMinDistance = 800,
	orbRemoteCollectBatch = false,
	autoClaimRankRewards = true,
	claimInterval = 0.35,
	claimDebounce = 0.28,
	autoRankUpGui = true,
	rankUpGuiInterval = 1.2,
	autoDismissRankUpUi = true,
	rankUpDismissInterval = 0.32,
	autoDismissMasteryPerkUi = true,
	masteryPerkDismissInterval = 0.32,
	autoEnableAutoFarm = true,
	autoFarmEnableInterval = 15,
	autoFarmReenableOnZoneChange = true,
	farmSignalNearbyEnabled = false,
	farmMultiHitCount = 1,
	tutorialHideGoalArrow = true,
	tutorialArrowInterval = 2,
	autoBuyZones = true,
	-- Не покупать следующую зону / не уходить на max farm teleporter, пока в текущей зоне активен random event из списка (CoinJar, ItemJar, …).
	blockZoneProgressWhileRandomEventActive = true,
	-- При behind max-owned всё ещё телепорт на max zone даже если в текущей зоне активен blocking random event (прогресс не душится).
	blockZoneProgressAllowTeleportWhenBehindMax = true,
	blockZoneProgressRandomEventIds = { "CoinJar", "ItemJar", "Comet", "Pinata", "LuckyBlock" },
	ignoreZoneGateQuests = false,
	zonePurchaseInterval = 0.55,
	teleportToMaxFarmZone = true,
	teleportMaxZoneClientPivotOnly = false,
	teleportClientPivotWhenSameZone = false,
	teleportClientPivotNearStuds = 32,
	questEggTeleportClientPivotOnly = false,
	teleportInterval = 10,
	teleportPivotYOffset = 3,
	teleportPivotRepeatCount = 5,
	teleportPivotRepeatDelayFrames = 1,
	teleportCannonWorkaround = false,
	-- После Teleports_RequestTeleport не вызывать PivotTo-повторы (конфликт с пушкой/состоянием канона).
	teleportPivotRepeatAfterServerTeleport = false,
	-- То же для телепорта к яйцу квеста по сети.
	questEggTeleportPivotRepeatAfterServer = false,
	autoDismissRebirthUi = true,
	rebirthDismissInterval = 0.28,
	hatchAfterPivotDelay = 0.38,
	hatchBusyHoldSeconds = 2.6,
	-- Скрытый hatch: armHatchBusyEnd + блок телепорта, пока живёт async-пайплайн (дольше обычных 2.6s).
	hatchBusyHoldSecondsHidden = 14,
	hatchAsyncTeleportBlockSeconds = 18,
	hatchAsyncPostPipelineGrace = 3,
	-- После вылупа снять hatchBusy раньше таймера, когда игра уже не в OpeningEgg / HatchingCmds (иначе фарм простаивает 15–20с).
	hatchBusyEarlyRelease = true,
	hatchBusyEarlyReleaseMinDelay = 0.55,
	hatchBusyEarlyReleaseMaxWait = 24,
	hatchBusyEarlyReleasePoll = 0.22,
	preferZoneEggWhenProgress = true,
	questEggTeleportIfWrongZone = true,
	-- Пауза pivot/hatch assist к физическому яйцу, если EggsUtil.GetEggPart вернул nil (меньше спама и кликов).
	eggPhysicalPartMissingCooldown = 10,
	--- Перед AttemptHatch: pivot + пауза + проверка дистанции до стойки (нет «too far» в холостую).
	hatchRequireNearEggBeforeAttempt = true,
	hatchMaxDistanceToEggStuds = 96,
	--- После fail gate или AttemptHatch «too far»: не дергать progress-hatch N секунд.
	progressHatchBackoffOnProximityFailSec = 18,
	--- Снять hatchBusy/guard сразу при AttemptHatch false + too far (фарм/телепорты не ждут конца holdHidden).
	hatchAbortBusyOnAttemptFail = true,
	advancedRemoteFarm = true,
	remoteFarmUseMaxZoneAnchor = true,
	-- Если не удаётся телепорт на max-owned (пушка / You can't do that right now), фармить брейкаблы по текущей зоне (Tech World и т.д.).
	remoteFarmAnchorCurrentZoneWhenCantTeleportMax = true,
	remoteFarmRadiusMultiplier = 2.4,
	remoteFarmOrbMagnetMultiplier = 1.45,
	remoteFarmSkipMaxZoneTeleport = false,
	remoteFarmSkipBreakablePull = false,
	forceTeleportWhenBehindMaxZone = true,
	autoClickReturnToAreaButton = true,
	returnToAreaClickInterval = 2,
	crossPlaceAutoReload = true,
	crossPlaceReloadUrl = "https://raw.githubusercontent.com/topzurdo/DoNotTryfindmyreposssssalsooa/refs/heads/main/auto_rank.lua",
	crossPlaceReloadReadfile = "",
	crossPlaceReloadDelaySec = 3,
	teleportToBreakableFarmCenter = true,
	farmBreakablePullInterval = 1.15,
	farmBreakableMinDist = 20,
	farmBreakableYOffset = 5,
	farmBreakableSpawnPartPriority = { "Main", "Easy", "VIP" },
	farmExplosiveBreakableAssist = true,
	farmExplosiveAssistInterval = 2.8,
	farmExplosiveAssistRequireWorld2 = true,
	farmExplosiveAssistWhenDealingDamage = true,
	farmExplosiveAssistPullToFarmBox = true,
	farmExplosiveAssistPreferOrder = { "TNT Crate", "TNT" },
	questAssistEnabled = true,
	questAssistInterval = 0.65,
	questTeleportToTarget = true,
	questTeleportMinDist = 14,
	questTeleportYOffset = 6,
	questAssistSkipFarmTeleportWhenObjective = true,
	questBlockOnGuiTransition = false,
	questAutoUnlockEgg = true,
	questEggUnlockCooldown = 8,
	questAutoHatch = true,
	questAutoHatchAnytime = false,
	questHatchAssistInterval = 1.1,
	hatchClampToAffordableAmount = true,
	-- Верхняя граница батча (ещё ограничивается EggCmds.GetMaxHatch и safeMode → 3).
	hatchMaxBatchAllowed = 10,
	hatchPreferAffordableEggInZone = true,
	hatchPreferAffordableEggGlobally = true,
	allowInfinityEggWithoutQuest = false,
	infinityEggQuestKeywords = { "infinity", "infinity egg", "infinityegg" },
	questAssistObjectiveKeywords = true,
	questSpawnInventoryBreakables = true,
	questSpawnInventoryBreakablesInterval = 2.75,
	-- Не расходовать Misc на gift/comet если текст только про мировые спавны — но цели про coin/item jar («…in best area») не резать (см. tryQuestSpawnInventoryBreakablesFromBlob).
	questSpawnInventorySkipWorldSpawnObjectives = true,
	-- Тексты целей Rank (справа) без GoalCmds — скрейп GUI.Rank / GoalsSide для Comet/Jar спавна при no_goal.
	questScrapeRankGoalsForMiscSpawn = true,
	questRankGoalsGuiScrapeInterval = 2.0,
	questRankGoalsGuiScrapeMaxLabels = 320,
	-- Синт-цели Rank→GetEnterPart (Instances): выкл. — не тянуть к Fishing/Dig-порталам, идём дальше по другим квестам.
	questSynthRankTrackedFromGui = false,
	-- RankGuiSynth (GetEnterPart): не Leave из инстанса и не Return-to-max, пока TTL активен.
	questSynthRankProtectInstanceFromAutoLeave = true,
	questSynthRankSuppressReturnToArea = true,
	questSynthRankProtectTtlSeconds = 180,
	questTeleportCanTeleportLogThrottleSeconds = 15,
	autoConsumeBuffs = true,
	autoConsumeBuffsInInstance = false,
	questConsumePotions = true,
	questConsumePotionsInterval = 1.35,
	questConsumePotionsOnlyWhenNoneActive = false,
	questConsumePotionBulk = true,
	questConsumePotionsPreferMaxTier = true,
	questConsumeHonorObjectivePotionTier = true,
	-- При no_goal брать текст «Use Tier I Potions» из PlayerGui + не блокировать Use из‑за активного баффа того же типа.
	questConsumeScrapeGuiForPotionTier = true,
	-- Если false: текст «Tier I» из PlayerGui не фиксирует тир — пьём лучшие зелья (scraped часто ловит низкий тир не из квеста).
	questConsumeScrapedPotionTierExactMatch = false,
	questConsumeGuiScrapeInterval = 1.85,
	questConsumeGuiScrapeMaxLabels = 500,
	questConsumeBypassActiveBuffForTierForced = true,
	questConsumeIgnoreOnlyWhenNoneWhenTierForced = true,
	questConsumeFruits = true,
	questConsumeFruitsInterval = 1.5,
	questConsumeFruitMaxAtOnce = 20,
	questConsumeFruitsPreferMaxTier = true,
	autoConsumeConsumables = true,
	autoConsumeConsumablesInterval = 2.2,
	autoConsumeConsumableBlocklist = {
		"Mining Bomb",
		"Mining TNT",
		"Mining TNT Crate",
		"Mining Nuclear TNT Crate",
		"Mining Bejeweled TNT Crate",
		"TNT",
	},
	questClickGuiTargets = true,
	questGuiClickInterval = 0.38,
	questPrioritizeListedGoalGenerators = true,
	questGoalGeneratorPrioritySubstrings = {
		"eggs",
		"zone",
		"unlock castle",
		"side buttons",
		"upgrades",
		"instances",
		"return to farm",
		"use enchant",
		"use potion",
		"keys",
		"trading plaza",
		"redeem rank reward",
		"machines",
		"rainbow machine",
		"rebirth shrines",
		"egg slots",
		"gold machine",
		"upgrade potions machine",
		"upgrade enchants machine",
		"pet slots",
		"travel to tech",
		"travel to void",
		"traverse void islands",
		"traverse from void spawn",
		"travel to fantasy",
		"fishingevent",
		"farmingworld",
		"halloweenworld",
		"placefarm",
		"claimfarm",
		"claimfarming",
		"spendfarm",
		"farmingtoken",
		"halloweentrick",
		"placehalloween",
		"newhalloween",
		"claimhalloween",
		"castfishing",
		"catchfish",
		"sellfish",
		"buyboat",
	},
	questEquipEnchants = true,
	questEquipEnchantInterval = 2.2,
	--- Пока активен hatch-пайплайн: не снимать enchant «для апгрейда тира» каждый тик (меньше Unequip spam).
	enchantsSkipTierUpgradeWhileHatchBusy = true,
	dynamicEnchantLoadout = true,
	enchantFarmPriority = {
		"Strong Pets",
		"Tap Power",
		"Criticals",
		"Coins",
		"Treasure Hunter",
		"Diamonds",
		"Magnet",
		"Walkspeed",
	},
	enchantFarmPriorityEarlyZones = {
		"Strong Pets",
		"Tap Power",
		"Criticals",
		"Coins",
		"Treasure Hunter",
		"Diamonds",
		"Magnet",
		"Walkspeed",
	},
	enchantFarmPriorityEarlyMaxZoneNumber = 159,
	enchantHatchPriority = {
		"Lucky Eggs",
		"Rainbow Eggs",
		"Super Shiny Hunter",
		"Shiny Hunter",
		"Huge Hunter",
		"Fortune",
		"Fruity",
	},
	questAutoPlaceFlag = true,
	questPlaceFlagInterval = 2,
	questAutoPlaceFlagWithoutTrackedGoal = true,
	questFlagNameFallbackOrder = {
		"Strength Flag",
		"Magnet Flag",
		"Hasty Flag",
		"Shiny Flag",
		"Rainbow Flag",
	},
	-- true: не слать синтетический Mouse.Button1Down по всем коннекшенам (ломает чужой UI).
	skipEggGuiClickWhenHiddenHatch = true,
	-- Сначала клик по конкретной кнопке «tap to open», синтетическую мышь — только если не вышло.
	eggOpeningPreferGuiButtonOverSyntheticMouse = true,
	autoBuyEggSlots = true,
	eggSlotPurchaseInterval = 1,
	eggSlotMaxPurchasesPerPulse = 3,
	eggSlotPurchaseTryUnlocked = true,
	autoBuyEquipSlots = true,
	equipSlotPurchaseInterval = 1,
	equipSlotMaxPurchasesPerPulse = 3,
	machinePurchaseFailureCooldown = 6,
	machineNotOwnedCooldown = 30,
	autoBuyCheapestUpgrade = true,
	upgradePurchaseInterval = 1.5,
	autoDaycare = true,
	autoDaycareInterval = 20,
	autoDaycareMaxClaimsPerTick = 1,
	questIgnoreMinigames = true,
	questIgnoreInstancesGenerator = false,
	questNormalizeNilGoalPriority = true,
	questMinigameObjectiveSubstrings = {
		"fishing",
		"digsite",
		"advanced digsite",
		"chest rush",
		"atlantis",
		"obby",
		"falling",
		"sled",
		"woodcutting",
		"diamond wheel",
		"flower garden",
		"ice obby",
		"jungle obby",
		"pyramid",
		"millionaire run",
		"easy obby",
		"hoverboard",
		"enchant empowering",
	},
	questBlockedObjectiveSubstrings = {},
	-- AdvancedDigsite: без лопаты из Fossil merchant клиент кидает Message — спам промпта входа бессмысленен.
	-- Валюта покупки — не Diamonds: отдельный слот HUD "Digsite" = CurrencyCmds/Get("Digsite"), копится в инстансе Digsite
	-- (DigsiteChests / руды в __DIRECTORY, см. Currency | Digsite + DigsiteMerchant).
	questBlockDigsiteEntryWithoutShovel = true,
	-- Блокировать только Advanced (базовый Digsite нужен чтобы фармить Digsite coins и купить Normal Shovel).
	questBlockAdvancedDigsiteOnlyWithoutShovel = true,
	-- Если true: лопата "Flimsy" не считается достаточной для входа Advanced (сообщение игры про merchant).
	questAdvancedDigsiteFlimsyShovelIsInsufficient = true,
	questAutoLeaveBlockedInstances = true,
	questBlockedInstanceIds = {
		"Fishing",
		"AdvancedFishing",
		"FishingEvent",
		"Digsite",
		"AdvancedDigsite",
		"Woodcutting",
		"FlowerGarden",
		"Atlantis",
		"ChestRush",
		"DiamondWheelInstance",
		"SpawnObby",
		"IceObby",
		"JungleObby",
		"PyramidObby",
		"HoverboardTechObby",
		"MillionaireRun",
		"LuckyBlocks",
		"EnchantEmpoweringInstance",
		"Minefield",
	},
	minigameAssistMode = "skip",
	instanceIdsForceLeave = nil,
	-- Авто-прохождение мини-игр (obby/dig/fish/…) по умолчанию выключено — список пустой.
	minigameAutoPlayInstanceIds = {},
	minigameAllowQuestInstancesWhenComplete = true,
	minigameAssistTickInterval = 0.16,
	minigameStuckLeaveSeconds = 90,
	minigameObbyFinishSearchDepth = 26,
	minigameObbyFinishPartNames = { "Finish", "Reward", "Win", "Goal", "End" },
	minigameObbyPreferCheckpointFallback = true,
	minigameObbyTouchNearbyParts = true,
	minigameObbyFireChildPrompts = true,
	minigameWave2SearchDepth = 14,
	minigameWave2MaxPromptsPerTick = 8,
	autoHatchProgressWithoutQuest = true,
	-- При no_goal из-за missing GoalCmds/FFlags или при generators>0 но validCallbacks==0 (executor ломает Callback): не крутить слепой hatching, а отдавать приоритет автопрогрессии зон.
	autoHatchProgressWhenGoalModulesMissing = false,
	-- Если false: при уже выбранной не-яйцовой цели (Machines, зона, …) не крутить progress-hatch параллельно — именно это даёт спам скрытых яиц при «Claim diamonds» и т.п.
	autoHatchProgressWhenNonEggQuest = false,
	autoHatchProgressCooldown = 10,
	questMachineGuiStuckMaxClicks = 22,
	questMachineGuiStuckWindowSec = 45,
	questMachineGuiStuckGeneratorSubstrings = {
		"upgrade potions machine",
		"upgrade enchants machine",
	},
	hatchReserveCurrencyForNextZone = true,
	-- Если true: при progress-only вылупе НЕ резервировать монету на следующую зону (иначе постоянный no_currency / reserve_next при фарме без квеста).
	hatchReserveSkipForProgressOnly = true,
	hatchNextZoneReserveMultiplier = 1.05,
	hatchReserveForNextZoneEvenWhenQuestIncomplete = true,
	-- Если дорогое яйцо не вылупить из‑за резерва на следующую зону — искать дешевле среди яиц зоны GetMaxOwnedZone().
	hatchProgressTryCheaperEggWhenReserveBlocks = true,
	hatchProgressFallbackEggMaxOwnedZoneOnly = true,
	-- Снять hatchAsyncGuard вместе с hatchBusy, когда клиент уже не OpeningEgg (убирает минуты «hatch_busy» при pulse.flags=false).
	hatchAsyncGuardClearWithHatchBusyEarlyRelease = true,
	hatchBusyWatchdogExtra = 10,
	autoEquipBestPetsEnabled = true,
	autoEquipBestPetsInterval = 14,
	autoPickStarterPetsEnabled = true,
	autoPickStarterPet1 = "Axolotl",
	autoPickStarterPet2 = "Cat",
	autoPickStarterPetsInterval = 1.5,
	hideEggHatching = true,
	autoClickEggOpeningPrompt = true,
	eggOpeningOnlyWhenOpening = true,
	eggOpeningPromptClickInterval = 0.65,
	eggOpeningPromptIntervalHiddenHatch = 0.25,
	eggOpeningPostInvokeBurstCount = 1,
	eggOpeningPostInvokeBurstDelay = 0.12,
	eggOpeningPromptCenterFallback = false,
	eggOpeningGuiScanInterval = 0.22,
	pivotBeforeRemotePurchases = true,
	machineSearchRadius = 2500,
	machineTeleportYOffset = 6,
	hatchTeleportNearEgg = true,
	hatchEggProximity = 36,
	hatchEggPivotYOffset = 8,
	autoCloseMachineTabs = true,
	autoCloseTabDelay = 0.22,
	autoCloseMachineTabIds = nil,
	autoCloseTabUseForce = false,
	executorGuiClickFallbacks = true,
	questUseFireClickDetector = false,
	questUseFireTouchInterest = false,
	questTravelWorldDirectNetwork = true,
	questTravelWorldDirectNetworkInterval = 2.6,
	questTravelTechRequireRebirth4 = true,
	-- Если после RequestTechRocket остаёмся в основном мире без IsTeleportingWorld2 — позже повторяем удалёнку + триггер ракеты Rainbow Road.
	-- Только Network.Fire(RequestTechRocket); без Pivot к ракете / fire ProximityPrompt (дубль с «пушкой»).
	questTravelTechRocketPhysicalEngage = false,
	-- Мин. сек между двумя RequestTechRocket (resolve + stuck retry, forceThrottle и т.д.). 0 — выключить анти-дубль.
	questTravelTechRocketMinGapSec = 0.15,
	questTravelTechRetryEnabled = true,
	questTravelTechRetryStuckAfterSec = 7,
	questTravelTechRetryEverySec = 4.5,
	questTravelTechRetryMaxAttempts = 12,
	-- GoalCmds в экзекьюторе часто даёт no_goal без tracked — при уже max зоне W1 и Rainbow Road давим RequestTechRocket + ракету.
	questTravelTechWhenNoGoalEnabled = true,
	questTravelTechWhenNoGoalInterval = 10,
	questTravelTechWhenNoGoalRequireRainbowRoad = true,
	farmUseFireClickDetectorFallback = false,
	debugLogInvokes = false,
	kickGuardTryBlockClientKick = true,
	kickGuardKickLog = true,
	kickGuardBlockTeleportToLobby = false,
	kickGuardBlockTeleportToPlaceIds = {},
	executorVirtualGuiClick = false,
	log = false,
	verboseLog = true,
	fileLogEnabled = true,
	fileLogPath = "AutoRank_debug.log",
	fileLogResetOnStart = true,
	fileLogVerbose = true,
	traceInterval = 4,
	ensureModulesInterval = 0.35,
	-- После queue_on_teleport / смены Place дефолт 3с оставлял все Client-модули nil → спам modules_missing, пустой фарм, GoalCmds_missing. Ставь >0 только если нужна искусственная пауза.
	ensureModulesInitialDelaySec = 0,
	-- Пока действует задержка выше — не слать verbose pulse (ложные pulse.*).
	verbosePulseSkipDuringModulesDefer = true,
	heartbeatErrorWarn = true,

	disableBuiltInAutoTapper = true,
	disableBuiltInAutoTapperInterval = 2.0,

	autoRedeemFreeGifts = true,
	freeGiftsCheckInterval = 2,
	freeGiftsMaxClaimsPerTick = 12,

	autoOpenInstantLootboxes = true,
	autoOpenNonInstantLootboxes = false,
	lootboxOpenInterval = 1.5,
	lootboxBatchAmount = 25,

	-- Misc инвентарь: сумки/бандлы через Network GiftBag_Open (см. ActionMenu Misc в клиенте).
	autoOpenMiscGiftBags = true,
	autoOpenMiscGiftBagsInterval = 4,
	autoOpenMiscGiftBagsMaxPerTick = 2,
	miscGiftBagAssertionFailureCooldownSec = 300,
	-- После assertion: паузы по uid (сек), затем giftBagAssertionMaxRetriesPerSession и abandon до перезапуска.
	giftBagAssertionBackoffSeconds = { 30, 60, 120, 300 },
	giftBagAssertionMaxRetriesPerSession = 5,
	giftBagTooFastBaseDelaySec = 1.5,
	giftBagTooFastBackoffMultiplier = 1.5,
	giftBagTooFastMaxDelaySec = 8,
	giftBagTooFastSuccessDecay = 0.85,
	autoOpenMiscGiftBagIds = {
		"Large Gift Bag",
		"Gift Bag",
		"Fruit Bundle",
		"Potion Bundle",
		"Enchant Bundle",
		"Large Enchant Bundle",
		"Large Potion Bundle",
		"Flag Bundle",
		"Toy Bundle",
		"Diamond Gift Bag",
		"Global Event Gift",
		"Seed Bag",
		"Charm Stone",
		"Mini Chest",
		"Rainbow Mini Chest",
	},

	autoConsumeEnabled = true,
	-- На том же hbIntervalConsumables уже идёт AR.Cons.tick (флаги/зелья по id). Legacy-квестовые зелья по тиру иначе могут сработать в том же heartbeat-движении вторым расходом.
	consumablesLegacySkipQuestPotionsWhenAutoConsume = false,
	consumablesTickInterval = 2,
	consumeFlagsHasty = true,
	consumeFlagsStrength = true,
	consumeFlagsMagnet = true,
	-- Не ставить Magnet Flag если и так включены collectOrbs + усиление магнита орбов (дублирование смысла).
	consumeSkipMagnetFlagWhenOrbMagnet = true,
	consumeSprinklers = true,
	-- Спавн за один вызов Consume (игра иначе может съесть maxPlace сразу).
	consumeSprinklerMaxPerInvoke = 1,
	-- 0 = всегда пробовать спринклер в зоне. Иначе только когда в радиусе фарма мало брейкаблов (очистили кольцо / ждём спавн).
	consumeSprinklerOnlyWhenInRadiusBelow = 10,
	consumeSprinklerSparseMinRawTapOk = 12,
	consumeDamagePotion = true,
	consumeRainbow = true,
	consumeShiny = true,
	consumeHugeHunter = true,
	consumeToyBone = true,
	consumeToyBall = true,
	consumeSqueakyToy = true,
	consumeMaxActionsPerTick = 3,
	consumeReserveHasty = 0,
	consumeReserveStrength = 0,
	consumeReserveMagnet = 0,
	consumeReserveSprinkler = 0,
	consumeReserveDamagePotion = 0,
	consumeReserveRainbow = 0,
	consumeReserveShiny = 0,
	consumeReserveHugeHunter = 0,
	consumeReserveToyBone = 0,
	consumeReserveToyBall = 0,
	consumeReserveSqueakyToy = 0,
	consumeFlagIdHasty = "Hasty Flag",
	consumeFlagIdStrength = "Strength Flag",
	consumeFlagIdMagnet = "Magnet Flag",
	consumeSprinklerId = "Breakable Sprinkler",
	consumePotionIdDamage = "Damage",
	consumePotionIdRainbow = "Lucky",
	consumePotionIdShiny = "Diamonds",
	consumePotionIdHugeHunter = "Huge",
	consumeToyIdBone = "Toy Bone",
	consumeToyIdBall = "Toy Ball",
	consumeToyIdSqueaky = "Squeaky Toy",
	consumeToyRemoteBone = "ToyBone_Consume",
	consumeToyRemoteBall = "ToyBall_Consume",
	consumeToyRemoteSqueaky = "SqueakyToy_Consume",
	consumeTrustServerInventory = false,
	consumeFailureCooldown = 8,
	consumeDebugLog = false,

	netRateLimitEnabled = true,
	netRateLimitPerSec = 18,
	netRateLimitWindow = 1.0,
	netRateLimitDefaultPriority = 5,
	netRateLimitFarmPriority = 1,
	netRateLimitPurchasePriority = 10,

	petsAlwaysFarmEnabled = true,
	petsAlwaysFarmTickInterval = 8.0,
	petsAlwaysFarmListenForceDisable = true,

	hbSchedulerEnabled = true,
	hbIntervalDealDamage = 0,
	hbIntervalDismissUI = 0.32,
	hbIntervalAutoBuy = 0.5,
	hbIntervalEquipPets = 2.0,
	hbIntervalConsumables = 2.0,
	hbIntervalFreeRewards = 2,
	hbIntervalLootbox = 1.5,
	hbIntervalQuestAssist = 0.65,
	hbIntervalAutoFarmEnable = 1.0,
	hbIntervalEnsureModules = 0.35,
}
